Feature/Purchase Order
felipeticiani-meli/projeto_integrador pull request #31
Opened 2022-08-10 15:50 UTC by brunavottri

2022-08-10 18:36 UTC, pealmeida-meli requested changes, later dismissed

2022-08-10 18:36 UTC, pealmeida-meli commented on src/main/java/com/mercadolibre/bootcamp/projeto_integrador/model/Buyer.java
> +    @OneToMany(mappedBy = "buyerId", cascade = CascadeType.ALL)
```suggestion
    @OneToMany(mappedBy = "buyer", cascade = CascadeType.ALL)
```

2022-08-12 16:39 UTC, bdonadel commented on src/main/resources/application.properties.example
> -spring.jpa.hibernate.ddl-auto = update
Acho que é melhor não excluir esse arquivo

2022-08-12 23:47 UTC, thiagosordiMELI approved these changes

2022-08-12 23:50 UTC, merged